import type { Template } from '@/lib/types'

export const MOCK_TEMPLATES: Template[] = [
  // LinkedIn Carousel
  { id: 'lt-01', title: 'Fintech 101: 5 Things Every Lagos Millennial Should Know', designer_name: 'Adaeze Okafor', category: 'LinkedIn Carousel', industry_tags: ['Fintech','Finance'], preview_url: 'https://placehold.co/1280x720/0f172a/3b82f6?text=Fintech+101', asset_url: null, price: 0, trend_tags: ['Educational carousels','Thought leadership','Audience growth','Trust building'], downloads: 2847, rating: 4.8, active: true, created_at: '2026-04-01T00:00:00Z' },
  { id: 'lt-02', title: 'The Startup Pitch Deck Carousel', designer_name: 'Emeka Obi', category: 'LinkedIn Carousel', industry_tags: ['SaaS','Tech','Fintech'], preview_url: 'https://placehold.co/1280x720/1e1b4b/818cf8?text=Pitch+Deck', asset_url: null, price: 0, trend_tags: ['Investor outreach','Product launches','Founder storytelling','B2B positioning'], downloads: 1203, rating: 4.5, active: true, created_at: '2026-04-05T00:00:00Z' },
  { id: 'lt-03', title: 'Competitor Takedown: Why Founders Are Switching', designer_name: 'Chidi Nwachukwu', category: 'LinkedIn Carousel', industry_tags: ['SaaS','Fintech','E-commerce'], preview_url: 'https://placehold.co/1280x720/172554/60a5fa?text=Competitor+Takedown', asset_url: null, price: 3500, trend_tags: ['Competitive positioning','Conversion content','Decision-stage buyers','Brand differentiation'], downloads: 891, rating: 4.7, active: true, created_at: '2026-04-10T00:00:00Z' },
  { id: 'lt-04', title: 'Founder Story: From ₦0 to ₦10M MRR', designer_name: 'Femi Adebayo', category: 'LinkedIn Carousel', industry_tags: ['SaaS','Fintech'], preview_url: 'https://placehold.co/1280x720/0c1445/93c5fd?text=Founder+Story', asset_url: null, price: 2500, trend_tags: ['Founder-led content','Brand credibility','Community building','Viral potential'], downloads: 654, rating: 4.6, active: true, created_at: '2026-04-15T00:00:00Z' },
  { id: 'lt-05', title: 'Product Feature Drop: 7 Slides That Convert', designer_name: 'Seun Olatunji', category: 'LinkedIn Carousel', industry_tags: ['SaaS','Tech'], preview_url: 'https://placehold.co/1280x720/162032/7dd3fc?text=Feature+Drop', asset_url: null, price: 4000, trend_tags: ['Product launches','Feature announcements','User education','Engagement campaigns'], downloads: 432, rating: 4.4, active: true, created_at: '2026-04-20T00:00:00Z' },
  // Social Post
  { id: 'lt-06', title: 'Fashion Brand Launch Set (12 templates)', designer_name: 'Kemi Adeleke', category: 'Social Post', industry_tags: ['Fashion','Lifestyle','E-commerce'], preview_url: 'https://placehold.co/1080x1080/2d1b69/c4b5fd?text=Fashion+Launch', asset_url: null, price: 0, trend_tags: ['Brand launches','Instagram feed','Product reveals','Influencer campaigns'], downloads: 3210, rating: 4.9, active: true, created_at: '2026-03-20T00:00:00Z' },
  { id: 'lt-07', title: 'Food Story: Farm to Table Social Kit', designer_name: 'Chioma Eze', category: 'Social Post', industry_tags: ['Food & Beverage','Lifestyle'], preview_url: 'https://placehold.co/1080x1080/1c1917/a16207?text=Food+Story', asset_url: null, price: 0, trend_tags: ['Brand storytelling','Community engagement','Product photography captions','Seasonal campaigns'], downloads: 1876, rating: 4.7, active: true, created_at: '2026-03-25T00:00:00Z' },
  { id: 'lt-08', title: 'Ramadan & Eid Campaign Kit', designer_name: 'Habiba Yusuf', category: 'Social Post', industry_tags: ['E-commerce','Fashion','Food & Beverage'], preview_url: 'https://placehold.co/1080x1080/1a1a2e/c084fc?text=Ramadan+Kit', asset_url: null, price: 2000, trend_tags: ['Seasonal campaigns','Cultural marketing','Holiday promotions','Community reach'], downloads: 567, rating: 4.5, active: true, created_at: '2026-04-12T00:00:00Z' },
  // Video Script
  { id: 'lt-09', title: 'Fintech Explainer: How It Works in 60 Seconds', designer_name: 'Tunde Balogun', category: 'Video Script', industry_tags: ['Fintech','Finance'], preview_url: 'https://placehold.co/1280x720/111827/10b981?text=Fintech+Explainer', asset_url: null, price: 3000, trend_tags: ['Product explainers','Paid ads','Onboarding videos','App store previews'], downloads: 723, rating: 4.6, active: true, created_at: '2026-04-08T00:00:00Z' },
  { id: 'lt-10', title: 'Brand Documentary Script: The Origin Story', designer_name: 'Seun Olatunji', category: 'Video Script', industry_tags: ['Fashion','Lifestyle','E-commerce'], preview_url: 'https://placehold.co/1280x720/0f172a/34d399?text=Origin+Story', asset_url: null, price: 6000, trend_tags: ['Brand documentaries','Investor videos','Founder storytelling','Press features'], downloads: 298, rating: 4.8, active: true, created_at: '2026-04-18T00:00:00Z' },
  // Email
  { id: 'lt-11', title: 'Newsletter Header Pack (10 designs)', designer_name: 'Bayo Adeyemi', category: 'Email', industry_tags: ['SaaS','Fintech','E-commerce'], preview_url: 'https://placehold.co/800x600/f8fafc/1e293b?text=Newsletter+Headers', asset_url: null, price: 0, trend_tags: ['Weekly newsletters','Announcement emails','Re-engagement campaigns','Subscriber growth'], downloads: 4102, rating: 4.9, active: true, created_at: '2026-03-15T00:00:00Z' },
  { id: 'lt-12', title: 'Product Launch Email Sequence (5 emails)', designer_name: 'Amara Nwosu', category: 'Email', industry_tags: ['Fintech','SaaS','E-commerce'], preview_url: 'https://placehold.co/800x600/fffbeb/92400e?text=Launch+Sequence', asset_url: null, price: 4000, trend_tags: ['Product launches','Pre-launch hype','Waitlist conversion','Revenue campaigns'], downloads: 521, rating: 4.7, active: true, created_at: '2026-04-22T00:00:00Z' },
  { id: 'lt-13', title: 'Abandoned Cart Recovery Kit (3 emails)', designer_name: 'Folake Bello', category: 'Email', industry_tags: ['E-commerce','Fashion','Food & Beverage'], preview_url: 'https://placehold.co/800x600/fef3c7/78350f?text=Cart+Recovery', asset_url: null, price: 2500, trend_tags: ['Revenue recovery','E-commerce automation','Customer retention','Conversion optimisation'], downloads: 389, rating: 4.5, active: true, created_at: '2026-04-25T00:00:00Z' },
  // Landing Page
  { id: 'lt-14', title: 'Investment App Landing Page', designer_name: 'Ngozi Chukwu', category: 'Landing Page', industry_tags: ['Fintech','Finance'], preview_url: 'https://placehold.co/1440x900/ecfdf5/065f46?text=Investment+App', asset_url: null, price: 8000, trend_tags: ['App launches','Paid ad destinations','Sign-up conversion','Investor demos'], downloads: 187, rating: 4.9, active: true, created_at: '2026-04-28T00:00:00Z' },
  { id: 'lt-15', title: 'SaaS Free Trial Landing Page', designer_name: 'Dayo Adekunle', category: 'Landing Page', industry_tags: ['SaaS','Tech'], preview_url: 'https://placehold.co/1440x900/f0fdf4/14532d?text=SaaS+Free+Trial', asset_url: null, price: 7500, trend_tags: ['Trial sign-ups','Product-led growth','Demo requests','B2B acquisition'], downloads: 143, rating: 4.8, active: true, created_at: '2026-05-01T00:00:00Z' },
]
